// <auto-generated />
using System;
using FarmsApiProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FarmsApiProject.Migrations
{
    [DbContext(typeof(FarmDbContext))]
    [Migration("20221130100707_mig_03")]
    partial class mig_03
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FarmsApiProject.Models.Farm", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnimalIdentificationNo")
                        .HasColumnType("int");

                    b.Property<string>("AnimalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnimalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnimalType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorizedPersonel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FarmID")
                        .HasColumnType("int");

                    b.Property<int>("Liter")
                        .HasColumnType("int");

                    b.Property<int>("MilkingID")
                        .HasColumnType("int");

                    b.Property<int>("MilkingTime")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Farms");
                });
#pragma warning restore 612, 618
        }
    }
}
